services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Brussels
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=1
      - N8N_RUNNERS_ENABLED=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - MCP_BASE_URL=${MCP_BASE_URL:-}

    volumes:
      - ./workflows:/workflows
      - ./init.sh:/docker-entrypoint-init.d/init.sh
      - n8n_data:/home/node/.n8n

    entrypoint: ["/bin/sh", "/docker-entrypoint-init.d/init.sh"]

volumes:
  n8n_data:
